"""Tests for ``pyrxd.crypto.aead`` — XChaCha20-Poly1305 + chunked-aead-v1.

Three test layers:

1. **RFC vectors** — draft-irtf-cfrg-xchacha-03 Appendix A.3.1. This is
   the spec contract; if these fail, the entire TIMELOCK plan is invalid.
2. **Photonic interop vectors** — the fixture in
   ``tests/fixtures/photonic_timelock_vectors.json`` generated by the
   Node bridge script that calls Photonic's actual source. If these fail,
   pyrxd and Photonic disagree at the byte level — protocol incompat.
3. **Round-trip + footgun tests** — encrypt then decrypt, tampering
   detection, malformed input rejection.
"""

from __future__ import annotations

import hashlib
import json
import secrets
from pathlib import Path

import pytest

from pyrxd.crypto.aead import (
    CHUNK_SIZE,
    XCHACHA20_KEY_SIZE,
    XCHACHA20_NONCE_SIZE,
    ChunkedCiphertext,
    EncryptedChunk,
    decrypt_chunked,
    decrypt_xchacha20_poly1305,
    encrypt_chunked,
    encrypt_xchacha20_poly1305,
)

FIXTURES_PATH = Path(__file__).parent / "fixtures" / "photonic_timelock_vectors.json"


@pytest.fixture(scope="module")
def photonic_vectors() -> dict:
    return json.loads(FIXTURES_PATH.read_text())


# ────────────────────────────────────────────── RFC 8439 / xchacha draft ──


class TestRfcVectors:
    """draft-irtf-cfrg-xchacha-03 Appendix A.3.1 — the spec contract."""

    def test_xchacha20_poly1305_appendix_a31(self):
        plaintext = bytes.fromhex(
            "4c616469657320616e642047656e746c656d656e206f662074686520636c6173"
            "73206f66202739393a204966204920636f756c64206f6666657220796f75206f"
            "6e6c79206f6e652074697020666f7220746865206675747572652c2073756e73"
            "637265656e20776f756c642062652069742e"
        )
        aad = bytes.fromhex("50515253c0c1c2c3c4c5c6c7")
        key = bytes.fromhex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f")
        nonce = bytes.fromhex("404142434445464748494a4b4c4d4e4f5051525354555657")
        expected_ct_with_tag = bytes.fromhex(
            "bd6d179d3e83d43b9576579493c0e939572a1700252bfaccbed2902c21396cbb"
            "731c7f1b0b4aa6440bf3a82f4eda7e39ae64c6708c54c216cb96b72e1213b452"
            "2f8c9ba40db5d945b11b69b982c1bb9e3f3fac2bc369488f76b2383565d3fff9"
            "21f9664c97637da9768812f615c68b13b52e"
            "c0875924c1c7987947deafd8780acf49"
        )

        result = encrypt_xchacha20_poly1305(plaintext, key, nonce, aad)
        assert result == expected_ct_with_tag

        # Round-trip
        recovered = decrypt_xchacha20_poly1305(result, key, nonce, aad)
        assert recovered == plaintext


# ────────────────────────────────────────────── Photonic interop ──


class TestPhotonicInterop:
    """Byte-equivalence against the Photonic-generated fixture file."""

    def test_xchacha_small_byte_equal(self, photonic_vectors):
        v = photonic_vectors["xchacha20_poly1305"]
        key = bytes.fromhex(v["key"])
        nonce = bytes.fromhex(v["nonce"])
        aad = bytes.fromhex(v["aad"])
        plaintext = bytes.fromhex(v["small"]["plaintext"])
        expected = bytes.fromhex(v["small"]["ciphertext"])

        result = encrypt_xchacha20_poly1305(plaintext, key, nonce, aad)
        assert result == expected, "pyrxd and Photonic produce different XChaCha20-Poly1305 output"

    def test_xchacha_large_round_trip_via_sha256(self, photonic_vectors):
        """Large plaintext: assert sha256(pyrxd-decrypt(Photonic-ct)) ==
        sha256(plaintext_recorded_in_fixture). This catches any byte-level
        disagreement without committing 8KB of expected output."""
        v = photonic_vectors["xchacha20_poly1305"]
        # No direct large-plaintext bytes in fixture (only sha256), so this
        # test instead asserts large encrypt+decrypt round-trips internally
        # AND matches the recorded ciphertext_sha256.
        key = bytes.fromhex(v["key"])
        nonce = bytes.fromhex(v["nonce"])
        aad = bytes.fromhex(v["aad"])
        # Reconstruct PT_LARGE per the bridge script's algorithm
        pt_large = bytes((i * 13 + 3) & 0xFF for i in range(8192))
        assert hashlib.sha256(pt_large).hexdigest() == v["large"]["plaintext_sha256"]
        result = encrypt_xchacha20_poly1305(pt_large, key, nonce, aad)
        assert hashlib.sha256(result).hexdigest() == v["large"]["ciphertext_sha256"]

    def test_chunked_aead_small_decrypt(self, photonic_vectors):
        """Photonic-encrypted chunks decrypt to the same plaintext."""
        v = photonic_vectors["chunked_aead_small"]
        key = bytes.fromhex(v["key"])
        plaintext_hash = bytes.fromhex(v["plaintext_hash"])
        chunks = [
            EncryptedChunk(
                ciphertext=bytes.fromhex(c["ciphertext"]),
                nonce=bytes.fromhex(c["nonce"]),
            )
            for c in v["chunks"]
        ]
        chunked = ChunkedCiphertext(chunks=chunks, plaintext_hash=plaintext_hash)
        decrypted = decrypt_chunked(chunked, key, plaintext_hash)
        assert decrypted == bytes.fromhex(v["plaintext"])

    def test_chunked_aead_multi_decrypt(self, photonic_vectors):
        """Multi-chunk (3 chunks for 80KB plaintext) decrypt path."""
        v = photonic_vectors["chunked_aead_multi"]
        key = bytes.fromhex(v["key"])
        plaintext_hash = bytes.fromhex(v["plaintext_hash"])
        chunks = [
            EncryptedChunk(
                ciphertext=bytes.fromhex(c["ciphertext"]),
                nonce=bytes.fromhex(c["nonce"]),
            )
            for c in v["chunks"]
        ]
        assert len(chunks) == 3, "expected 3 chunks for 80KB plaintext"
        chunked = ChunkedCiphertext(chunks=chunks, plaintext_hash=plaintext_hash)
        decrypted = decrypt_chunked(chunked, key, plaintext_hash)
        assert len(decrypted) == v["plaintext_length"]
        assert hashlib.sha256(decrypted).hexdigest() == v["plaintext_sha256"]


# ────────────────────────────────────────────── round-trip + footguns ──


class TestRoundTrip:
    def test_xchacha_round_trip_random(self):
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        nonce = secrets.token_bytes(XCHACHA20_NONCE_SIZE)
        plaintext = b"hello, world" * 100
        aad = b"some-aad"
        ct = encrypt_xchacha20_poly1305(plaintext, key, nonce, aad)
        assert decrypt_xchacha20_poly1305(ct, key, nonce, aad) == plaintext

    def test_chunked_round_trip_small(self):
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        plaintext = b"short message"
        chunked = encrypt_chunked(plaintext, key)
        assert len(chunked.chunks) == 1
        recovered = decrypt_chunked(chunked, key, chunked.plaintext_hash)
        assert recovered == plaintext

    def test_chunked_round_trip_at_chunk_boundary(self):
        """Plaintext exactly equal to CHUNK_SIZE should produce 1 chunk."""
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        plaintext = bytes(CHUNK_SIZE)
        chunked = encrypt_chunked(plaintext, key)
        assert len(chunked.chunks) == 1
        assert decrypt_chunked(chunked, key, chunked.plaintext_hash) == plaintext

    def test_chunked_round_trip_just_over_boundary(self):
        """CHUNK_SIZE + 1 bytes should produce 2 chunks."""
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        plaintext = bytes(CHUNK_SIZE + 1)
        chunked = encrypt_chunked(plaintext, key)
        assert len(chunked.chunks) == 2
        assert decrypt_chunked(chunked, key, chunked.plaintext_hash) == plaintext

    def test_chunked_round_trip_three_chunks(self):
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        plaintext = bytes(CHUNK_SIZE * 2 + 100)
        chunked = encrypt_chunked(plaintext, key)
        assert len(chunked.chunks) == 3
        assert decrypt_chunked(chunked, key, chunked.plaintext_hash) == plaintext


class TestFootguns:
    def test_xchacha_wrong_key_fails(self):
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        nonce = secrets.token_bytes(XCHACHA20_NONCE_SIZE)
        ct = encrypt_xchacha20_poly1305(b"hi", key, nonce)
        wrong = bytes(32)
        with pytest.raises(ValueError, match="AEAD decryption failed"):
            decrypt_xchacha20_poly1305(ct, wrong, nonce)

    def test_xchacha_wrong_nonce_fails(self):
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        nonce = secrets.token_bytes(XCHACHA20_NONCE_SIZE)
        ct = encrypt_xchacha20_poly1305(b"hi", key, nonce)
        with pytest.raises(ValueError, match="AEAD decryption failed"):
            decrypt_xchacha20_poly1305(ct, key, bytes(24))

    def test_xchacha_tampered_ciphertext_fails(self):
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        nonce = secrets.token_bytes(XCHACHA20_NONCE_SIZE)
        ct = bytearray(encrypt_xchacha20_poly1305(b"hello, world", key, nonce))
        ct[0] ^= 0x01  # flip a bit
        with pytest.raises(ValueError, match="AEAD decryption failed"):
            decrypt_xchacha20_poly1305(bytes(ct), key, nonce)

    def test_xchacha_wrong_aad_fails(self):
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        nonce = secrets.token_bytes(XCHACHA20_NONCE_SIZE)
        ct = encrypt_xchacha20_poly1305(b"hi", key, nonce, b"good-aad")
        with pytest.raises(ValueError, match="AEAD decryption failed"):
            decrypt_xchacha20_poly1305(ct, key, nonce, b"bad-aad")

    def test_xchacha_rejects_wrong_key_size(self):
        with pytest.raises(ValueError, match="key must be 32"):
            encrypt_xchacha20_poly1305(b"hi", bytes(16), bytes(24))

    def test_xchacha_rejects_wrong_nonce_size(self):
        with pytest.raises(ValueError, match="nonce must be 24"):
            encrypt_xchacha20_poly1305(b"hi", bytes(32), bytes(12))

    def test_chunked_wrong_plaintext_hash_fails(self):
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        chunked = encrypt_chunked(b"some data", key)
        with pytest.raises(ValueError):
            decrypt_chunked(chunked, key, bytes(32))

    def test_chunked_tampered_chunk_fails(self):
        key = secrets.token_bytes(XCHACHA20_KEY_SIZE)
        chunked = encrypt_chunked(b"some data", key)
        # Flip a byte in chunk 0's ciphertext
        bad = bytearray(chunked.chunks[0].ciphertext)
        bad[0] ^= 0x01
        chunks_tampered = [
            EncryptedChunk(ciphertext=bytes(bad), nonce=chunked.chunks[0].nonce),
            *chunked.chunks[1:],
        ]
        bad_chunked = ChunkedCiphertext(chunks=chunks_tampered, plaintext_hash=chunked.plaintext_hash)
        with pytest.raises(ValueError):
            decrypt_chunked(bad_chunked, key, chunked.plaintext_hash)
