"""dMint V2 EPOCH + SCHEDULE covenant byte-match vs canonical Photonic.

Companion to ``test_dmint_v2_canonical.py`` (FIXED/ASERT/LWMA). Golden vectors
generated by running the canonical ``Radiant-Core/Photonic-Wallet`` ``dMintScript``
(``buildEpochDaaBytecode`` / ``buildScheduleDaaBytecode``) under ``bun`` and
captured verbatim. pyrxd's ``build_dmint_contract_script`` MUST reproduce them
byte-for-byte (#219).

EPOCH targets are ≤ 2^48 (the ``EPOCH_MAX_SAFE_TARGET`` overflow cap), so the
vectors use difficulty ≥ 32768. SHA256d, contractRef = aa*36, tokenRef = bb*36.
"""

from __future__ import annotations

import warnings

import pytest

from pyrxd.glyph.dmint import (
    DaaMode,
    DmintAlgo,
    DmintDeployParams,
    build_dmint_contract_script,
)
from pyrxd.glyph.dmint.types import MAX_SHA256D_TARGET as _MAX
from pyrxd.glyph.types import GlyphRef

_CONTRACT_REF = GlyphRef.from_bytes(bytes.fromhex("aa" * 36))
_TOKEN_REF = GlyphRef.from_bytes(bytes.fromhex("bb" * 36))

_GOLDEN: dict[str, tuple[dict, str]] = {
    "epoch_h0_el10_n2": (
        dict(
            height=0,
            max_height=1000,
            reward=1000,
            difficulty=100000,
            daa_mode=DaaMode.EPOCH,
            target_time=60,
            epoch_length=10,
            max_adjustment_log2=2,
        ),
        "00d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb02"
        "e80302e8030051013c040000000006a38d23d6e253bdc0c859797ea85d795d797ea87e5e7a7e"
        "aabc01147f77587f040000000088817600a26951797ca26959797600a07c5a97009c9a63c552"
        "799453798d8da353798e8ea47c9552799608ffffffffffffff7fa376519f63755168686b7575"
        "7575577ae500a069567ae600a06901d053797e0cdec0e9aa76e378e4a269e69d7eaa76e47b9d"
        "547a818b76537a9c537ade789181547ae6939d636c755279cd01d853797e016a7e886778de51"
        "9d7676009c63750100677660a163015093518067827c7e68684c54d8aaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad0bbbbbbbbbbbbbbbbbbbbbb"
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb02e80302e8030051013c7ec554"
        "80547c7e7e6c76009c63750100677660a163015093518067827c7e68687e5379ec78885379ea"
        "c0e9885379cc519d75686d7551",
    ),
    "epoch_h20_el10_n1": (
        dict(
            height=20,
            max_height=1000,
            reward=1000,
            difficulty=100000,
            daa_mode=DaaMode.EPOCH,
            target_time=60,
            epoch_length=10,
            max_adjustment_log2=1,
        ),
        "0114d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aad0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
        "02e80302e8030051013c040000000006a38d23d6e253bdc0c859797ea85d795d797ea87e5e7a"
        "7eaabc01147f77587f040000000088817600a26951797ca26959797600a07c5a97009c9a63c5"
        "52799453798da353798ea47c9552799608ffffffffffffff7fa376519f63755168686b757575"
        "75577ae500a069567ae600a06901d053797e0cdec0e9aa76e378e4a269e69d7eaa76e47b9d54"
        "7a818b76537a9c537ade789181547ae6939d636c755279cd01d853797e016a7e886778de519d"
        "7676009c63750100677660a163015093518067827c7e68684c54d8aaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad0bbbbbbbbbbbbbbbbbbbbbbbb"
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb02e80302e8030051013c7ec55480"
        "547c7e7e6c76009c63750100677660a163015093518067827c7e68687e5379ec78885379eac0"
        "e9885379cc519d75686d7551",
    ),
    "epoch_h5_el20_n4": (
        dict(
            height=5,
            max_height=1000,
            reward=1000,
            difficulty=50000,
            daa_mode=DaaMode.EPOCH,
            target_time=120,
            epoch_length=20,
            max_adjustment_log2=4,
        ),
        "55d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb02"
        "e80302e80300510178040000000007471b47acc5a700bdc0c859797ea85d795d797ea87e5e7a"
        "7eaabc01147f77587f040000000088817600a26951797ca26959797600a07c011497009c9a63"
        "c552799453798d8d8d8da353798e8e8e8ea47c9552799608ffffffffffffff7fa376519f6375"
        "5168686b75757575577ae500a069567ae600a06901d053797e0cdec0e9aa76e378e4a269e69d"
        "7eaa76e47b9d547a818b76537a9c537ade789181547ae6939d636c755279cd01d853797e016a"
        "7e886778de519d7676009c63750100677660a163015093518067827c7e68684c54d8aaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad0bbbbbbbbbb"
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb02e80302e80300"
        "5101787ec55480547c7e7e6c76009c63750100677660a163015093518067827c7e68687e5379"
        "ec78885379eac0e9885379cc519d75686d7551",
    ),
    "sched_1entry": (
        dict(
            height=0,
            max_height=1000,
            reward=1000,
            difficulty=10,
            daa_mode=DaaMode.SCHEDULE,
            target_time=60,
            schedule=((100, _MAX // 20),),
        ),
        "00d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb02"
        "e80302e8030054013c040000000008cccccccccccccc0cbdc0c859797ea85d795d797ea87e5e"
        "7a7eaabc01147f77587f040000000088817600a26951797ca26959790164a263750866666666"
        "66666606686b75757575577ae500a069567ae600a06901d053797e0cdec0e9aa76e378e4a269"
        "e69d7eaa76e47b9d547a818b76537a9c537ade789181547ae6939d636c755279cd01d853797e"
        "016a7e886778de519d7676009c63750100677660a163015093518067827c7e68684c54d8aaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad0bbbbbb"
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb02e80302e8"
        "030054013c7ec55480547c7e7e6c76009c63750100677660a163015093518067827c7e68687e"
        "5379ec78885379eac0e9885379cc519d75686d7551",
    ),
    "sched_3entry": (
        dict(
            height=0,
            max_height=1000,
            reward=1000,
            difficulty=10,
            daa_mode=DaaMode.SCHEDULE,
            target_time=60,
            schedule=((10, _MAX // 4), (50, _MAX // 8), (100, _MAX // 16)),
        ),
        "00d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb02"
        "e80302e8030054013c040000000008cccccccccccccc0cbdc0c859797ea85d795d797ea87e5e"
        "7a7eaabc01147f77587f040000000088817600a26951797ca26959790164a2637508ffffffff"
        "ffffff076759790132a2637508ffffffffffffff0f6759795aa2637508ffffffffffffff1f68"
        "68686b75757575577ae500a069567ae600a06901d053797e0cdec0e9aa76e378e4a269e69d7e"
        "aa76e47b9d547a818b76537a9c537ade789181547ae6939d636c755279cd01d853797e016a7e"
        "886778de519d7676009c63750100677660a163015093518067827c7e68684c54d8aaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad0bbbbbbbbbbbb"
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb02e80302e8030054"
        "013c7ec55480547c7e7e6c76009c63750100677660a163015093518067827c7e68687e5379ec"
        "78885379eac0e9885379cc519d75686d7551",
    ),
}


@pytest.mark.parametrize("label", list(_GOLDEN))
def test_epoch_schedule_byte_matches_canonical_photonic(label):
    kwargs, golden_hex = _GOLDEN[label]
    params = DmintDeployParams(contract_ref=_CONTRACT_REF, token_ref=_TOKEN_REF, algo=DmintAlgo.SHA256D, **kwargs)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        got = build_dmint_contract_script(params).hex()
    assert got == golden_hex, f"{label}: pyrxd EPOCH/SCHEDULE bytecode diverged from canonical Photonic"
